import { Poppins, Ubuntu } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"

const ubuntu = Ubuntu({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-ubuntu',
})

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata = {
  title: "Upmagic 🪄",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    shortcut: '/logo.svg',
    apple: '/logo.svg',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${ubuntu.variable} antialiased p-4`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
