import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata = {
  title: "Upmagic 🪄",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    shortcut: '/logo.svg',
    apple: '/logo.svg',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased p-4`}
      >
        {children}
      </body>
    </html>
  );
}
